// packages/use-wallet-solid/src/index.tsx
import { useStore } from '@tanstack/solid-store'
import algosdk from 'algosdk'
import { JSX, createContext, createMemo, onMount, useContext } from 'solid-js'
import type {
  NetworkId,
  WalletAccount,
  WalletId,
  WalletManager,
  WalletMetadata,
  WalletState
} from 'avm-wallet'

export * from 'avm-wallet'

interface WalletProviderProps {
  manager: WalletManager
  children: JSX.Element
}

const WalletContext = createContext<() => WalletManager>()

export const WalletProvider = (props: WalletProviderProps) => {
  const store = () => props.manager

  onMount(async () => {
    try {
      await props.manager.resumeSessions()
    } catch (error) {
      console.error('Error resuming sessions:', error)
    }
  })

  return <WalletContext.Provider value={store}>{props.children}</WalletContext.Provider>
}

export const useWalletManager = (): WalletManager => {
  const manager = useContext(WalletContext)
  if (!manager) {
    throw new Error('useWalletManager must be used within a WalletProvider')
  }
  return manager()
}

export interface Wallet {
  id: () => string
  metadata: () => WalletMetadata
  accounts: () => WalletAccount[]
  activeAccount: () => WalletAccount | null
  isConnected: () => boolean
  isActive: () => boolean
  connect: (args?: Record<string, any>) => Promise<WalletAccount[]>
  disconnect: () => Promise<void>
  setActive: () => void
  setActiveAccount: (address: string) => void
}

export function useWallet() {
  const manager = createMemo(() => useWalletManager())

  const algodClient = useStore(manager().store, (state) => state.algodClient)

  const walletStore = useStore(manager().store, (state) => state.wallets)

  const walletState = (walletId: WalletId): WalletState | null => walletStore()[walletId] || null

  const avmActiveWalletId = useStore(manager().store, (state) => state.avmActiveWallet)

  const avmActiveWallet = () => manager().getWallet(avmActiveWalletId() as WalletId) || null

  const avmActiveWalletState = () => walletState(avmActiveWalletId() as WalletId)

  const avmActiveWalletAccounts = () => avmActiveWalletState()?.accounts ?? null

  const avmActiveWalletAddresses = () =>
    avmActiveWalletAccounts()?.map((account) => account.address) ?? null

  const activeAccount = () => avmActiveWalletState()?.activeAccount ?? null

  const activeAddress = () => activeAccount()?.address ?? null

  const isWalletActive = (walletId: WalletId) => walletId === avmActiveWalletId()
  const isWalletConnected = (walletId: WalletId) =>
    !!walletState(walletId)?.accounts.length || false

  const activeNetwork = useStore(manager().store, (state) => state.activeNetwork)

  const setActiveNetwork = async (networkId: NetworkId): Promise<void> => {
    if (activeNetwork() === networkId) {
      return
    }

    console.info(`[Solid] Creating Algodv2 client for ${networkId}...`)

    const { token, baseServer, port, headers } = manager().networkConfig[networkId]
    const newClient = new algosdk.Algodv2(token, baseServer, port, headers)

    manager().store.setState((state) => ({
      ...state,
      activeNetwork: networkId,
      algodClient: newClient
    }))

    console.info(`[Solid] ✅ Active network set to ${networkId}.`)
  }

  const signTransactions = <T extends algosdk.Transaction[] | Uint8Array[]>(
    txnGroup: T | T[],
    indexesToSign?: number[]
  ): Promise<(Uint8Array | null)[]> => {
    const wallet = avmActiveWallet()
    if (!wallet) {
      throw new Error('No active wallet')
    }
    return wallet.signTransactions(txnGroup, indexesToSign)
  }

  const transactionSigner = (
    txnGroup: algosdk.Transaction[],
    indexesToSign: number[]
  ): Promise<Uint8Array[]> => {
    const wallet = avmActiveWallet()
    if (!wallet) {
      throw new Error('No active wallet')
    }
    return wallet.transactionSigner(txnGroup, indexesToSign)
  }

  return {
    avmActiveWalletId,
    walletStore,
    algodClient,
    activeNetwork,
    avmActiveWallet,
    avmActiveWalletAccounts,
    avmActiveWalletAddresses,
    avmActiveWalletState,
    activeAccount,
    activeAddress,
    isWalletActive,
    isWalletConnected,
    setActiveNetwork,
    signTransactions,
    transactionSigner,
    wallets: manager().wallets
  }
}

// packages/use-wallet-react/src/index.tsx
import { useStore } from '@tanstack/react-store'
import { NetworkId, WalletAccount, WalletManager, WalletMetadata } from 'avm-wallet'
import algosdk from 'algosdk'
import * as React from 'react'

export * from 'avm-wallet'

interface IWalletContext {
  manager: WalletManager
  algodClient: algosdk.Algodv2
  setAlgodClient: React.Dispatch<React.SetStateAction<algosdk.Algodv2>>
}

const WalletContext = React.createContext<IWalletContext | undefined>(undefined)

export interface Wallet {
  id: string
  metadata: WalletMetadata
  accounts: WalletAccount[]
  activeAccount: WalletAccount | null
  isConnected: boolean
  isActive: boolean
  connect: (args?: Record<string, any>) => Promise<WalletAccount[]>
  disconnect: () => Promise<void>
  setActive: () => void
  setActiveAccount: (address: string) => void
}

export const useWallet = () => {
  const context = React.useContext(WalletContext)

  if (!context) {
    throw new Error('useWallet must be used within the WalletProvider')
  }

  const { manager, algodClient, setAlgodClient } = context

  const activeNetwork = useStore(manager.store, (state) => state.activeNetwork)

  const setActiveNetwork = async (networkId: NetworkId): Promise<void> => {
    if (networkId === activeNetwork) {
      return
    }

    console.info(`[React] Creating Algodv2 client for ${networkId}...`)

    const { token = '', baseServer, port = '', headers = {} } = manager.networkConfig[networkId]
    const newClient = new algosdk.Algodv2(token, baseServer, port, headers)
    setAlgodClient(newClient)

    manager.store.setState((state) => ({
      ...state,
      activeNetwork: networkId
    }))

    console.info(`[React] ✅ Active network set to ${networkId}.`)
  }

  const walletStateMap = useStore(manager.store, (state) => state.wallets)
  const avmActiveWalletId = useStore(manager.store, (state) => state.avmActiveWallet)

  const wallets = React.useMemo(() => {
    return [...manager.wallets.values()].map((wallet): Wallet => {
      const walletState = walletStateMap[wallet.id]

      return {
        id: wallet.id,
        metadata: wallet.metadata,
        accounts: walletState?.accounts ?? [],
        activeAccount: walletState?.activeAccount ?? null,
        isConnected: !!walletState,
        isActive: wallet.id === avmActiveWalletId,
        connect: (args) => wallet.connect(args),
        disconnect: () => wallet.disconnect(),
        setActive: () => wallet.setActive(),
        setActiveAccount: (addr) => wallet.setActiveAccount(addr)
      }
    })
  }, [manager, walletStateMap, avmActiveWalletId])

  const avmActiveWallet = avmActiveWalletId ? manager.getWallet(avmActiveWalletId) || null : null
  const avmActiveWalletState = avmActiveWalletId ? walletStateMap[avmActiveWalletId] || null : null

  const avmActiveWalletAccounts = avmActiveWalletState?.accounts ?? null
  const avmActiveWalletAddresses = avmActiveWalletAccounts?.map((account) => account.address) ?? null
  const activeAccount = avmActiveWalletState?.activeAccount ?? null
  const activeAddress = activeAccount?.address ?? null

  const signTransactions = <T extends algosdk.Transaction[] | Uint8Array[]>(
    txnGroup: T | T[],
    indexesToSign?: number[]
  ): Promise<(Uint8Array | null)[]> => {
    if (!avmActiveWallet) {
      throw new Error('No active wallet')
    }
    return avmActiveWallet.signTransactions(txnGroup, indexesToSign)
  }

  const transactionSigner = (
    txnGroup: algosdk.Transaction[],
    indexesToSign: number[]
  ): Promise<Uint8Array[]> => {
    if (!avmActiveWallet) {
      throw new Error('No active wallet')
    }
    return avmActiveWallet.transactionSigner(txnGroup, indexesToSign)
  }

  return {
    wallets,
    algodClient,
    activeNetwork,
    avmActiveWallet,
    avmActiveWalletAccounts,
    avmActiveWalletAddresses,
    activeAccount,
    activeAddress,
    setActiveNetwork,
    setAlgodClient,
    signTransactions,
    transactionSigner
  }
}

interface WalletProviderProps {
  manager: WalletManager
  children: React.ReactNode
}

export const WalletProvider = ({ manager, children }: WalletProviderProps): JSX.Element => {
  const [algodClient, setAlgodClient] = React.useState(manager.algodClient)

  React.useEffect(() => {
    manager.algodClient = algodClient
  }, [algodClient, manager])

  const resumedRef = React.useRef(false)

  React.useEffect(() => {
    const resumeSessions = async () => {
      try {
        await manager.resumeSessions()
      } catch (error) {
        console.error('Error resuming sessions:', error)
      }
    }

    if (!resumedRef.current) {
      resumeSessions()
      resumedRef.current = true
    }
  }, [manager])

  return (
    <WalletContext.Provider value={{ manager, algodClient, setAlgodClient }}>
      {children}
    </WalletContext.Provider>
  )
}
